[project]
name = "elt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.0",
    "duckdb>=1.4.0",
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
]
